### ISSUE TITLE
nil pointer in (*Association).AcceptStream

### ISSUE THREAD

**Issue by maxhawkins** [pions/sctp#27]
### Your environment.
  - Version: d6da587e569babffe7246a351960353d77b4dff6

### What did you do?
I pushed to github and the CI ran the tests on my rtpdump [branch](https://github.com/pions/webrtc/pull/522).

### What happened?

```
=== RUN   TestDataChannel_ORTCE2E
Failed to read from data channel association closed
Failed to read from data channel association closed
Failed to accept data channel: The association is closed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7511fe]
goroutine 92 [running]:
github.com/pions/sctp.(*Association).AcceptStream(...)
	/home/travis/gopath/pkg/mod/github.com/pions/sctp@v1.4.2/association.go:579
github.com/pions/datachannel.Accept(0x0, 0x1, 0xc000000006, 0x28)
	/home/travis/gopath/pkg/mod/github.com/pions/datachannel@v1.2.0/datachannel.go:73 +0x3e
github.com/pions/webrtc.(*SCTPTransport).acceptDataChannels(0xc0000a64e0)
	/home/travis/build/pions/webrtc/sctptransport.go:133 +0x10d
created by github.com/pions/webrtc.(*SCTPTransport).Start
	/home/travis/build/pions/webrtc/sctptransport.go:96 +0x1a4
FAIL	github.com/pions/webrtc	7.619s
```

**Comment by enobufs** [comment]
It looks to me datachannel is calling AcceptStream() on a null (*Association).
https://github.com/pions/datachannel/blob/ddfecc436c71dfac799c539f13035f51be33867c/datachannel.go#L73
I guess, Not an sctp issue...

**Comment by Sean-Der** [comment]
Yea that looks right to me @enobufs !

Will move to `pions/webrtc` I don't know how we got a nil here, will dig into it :)
